[package]
name = "rust-s3-sia"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-s3 = "0.34.0-rc3"
tokio = { version = "1.36.0", features = ["full"] }

